- name: My first playbook
  hosts: all
  gather_facts: true
  tasks:

    # gather_facts needs to be set
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    # ansible_facts need to be gather for `when` clause to work
    - name: Run macos task
      ansible.builtin.command: pwd
      when: ansible_facts['distribution']=="MacOSX"

    - name: Run ubuntu task
      ansible.builtin.command: pwd
      when: ansible_facts['distribution']=="Ubuntu"
